function varargout = NS_CPM(varargin)
% NS_CPM MATLAB code for NS_CPM.fig
%      NS_CPM, by itself, creates a new NS_CPM or raises the existing
%      singleton*.
%
%      H = NS_CPM returns the handle to a new NS_CPM or the handle to
%      the existing singleton*.
%
%      NS_CPM('CALLBACK',hObject,eventData,handles,...) calls the local
%      function named CALLBACK in NS_CPM.M with the given input arguments.
%
%      NS_CPM('Property','Value',...) creates a new NS_CPM or raises the
%      existing singleton*.  Starting from the left, property value pairs are
%      applied to the GUI before NS_CPM_OpeningFcn gets called.  An
%      unrecognized property name or invalid value makes property application
%      stop.  All inputs are passed to NS_CPM_OpeningFcn via varargin.
%
%      *See GUI Options on GUIDE's Tools menu.  Choose "GUI allows only one
%      instance to run (singleton)".
%
% See also: GUIDE, GUIDATA, GUIHANDLES

% Edit the above text to modify the response to help NS_CPM

% Last Modified by GUIDE v2.5 10-Dec-2024 20:03:12

% Begin initialization code - DO NOT EDIT
gui_Singleton = 1;
gui_State = struct('gui_Name',       mfilename, ...
                   'gui_Singleton',  gui_Singleton, ...
                   'gui_OpeningFcn', @NS_CPM_OpeningFcn, ...
                   'gui_OutputFcn',  @NS_CPM_OutputFcn, ...
                   'gui_LayoutFcn',  @NS_CPM_LayoutFcn, ...
                   'gui_Callback',   []);
if nargin && ischar(varargin{1})
    gui_State.gui_Callback = str2func(varargin{1});
end

if nargout
    [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});
else
    gui_mainfcn(gui_State, varargin{:});
end
% End initialization code - DO NOT EDIT


% --- Executes just before NS_CPM is made visible.
function NS_CPM_OpeningFcn(hObject, eventdata, handles, varargin)
% This function has no output args, see OutputFcn.
% hObject    handle to figure
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% varargin   command line arguments to NS_CPM (see VARARGIN)

% Choose default command line output for NS_CPM
% web message



handles.output = hObject;

axes(handles.axes1);
axis image;

[a]=mfilename('fullpath');
[cdir, ~ ] = fileparts(a);
figobj=get(handles.figure1);
f = imread([cdir filesep 'icon' filesep 'spider3.png'],'BackgroundColor',figobj.Color);
h =imshow(f);
set(h,'ButtonDownFcn',@my_imButtonDfcn)

movegui(hObject, 'center')
% my_imButtonDfcn

addpath([cdir filesep 'functions']);
figName = figobj.Name;
currentVersion = figName(strfind(figName,' ')+1:end);

 
[webcontent, WebStatus]=urlread('https://neurospider.cn/projects/NST2021a.txt');
 

if WebStatus
    webcontent   = strrep(webcontent,char(10),''); %#ok<CHARTEN> 
    webcontent   = strrep(webcontent,char(13),'');


    [startIndex_v,endIndex_v] = regexp(webcontent,'@=@version: ');
    [startIndex_m,endIndex_m] = regexp(webcontent,'@=@message: ');
    [startIndex_w,endIndex_w] = regexp(webcontent,'@=@weburl: ');
    NSverson  = webcontent(endIndex_v+1:startIndex_m-1);
    webmsg    = webcontent(endIndex_m+1:startIndex_w-1);
    weburl    = webcontent(endIndex_w+1:end);
    if ~isequal(currentVersion,NSverson)
         opt.Default = 'Yes';opt.Interpreter='none';
         answer=questdlg(sprintf('a new version is available, check the new version here: \n %s',weburl),'update','Yes','No',opt);
%          switch answer
%              case 'Yes'
%                  web(weburl,'-browser');
%               
%          end
                 
    else
        if ~isempty(webmsg)
            msgbox(webmsg,'modal') 
        end
    end
    
       
end

% Update handles structure
guidata(hObject, handles);

% UIWAIT makes NS_CPM wait for user response (see UIRESUME)
% uiwait(handles.figure1);
function figure1_CreateFcn(hObject, eventdata, handles)
% hObject    handle to figure1 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% --- Outputs from this function are returned to the command line.
function varargout = NS_CPM_OutputFcn(hObject, eventdata, handles) 
% varargout  cell array for returning output args (see VARARGOUT);
% hObject    handle to figure
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Get default command line output from handles structure
varargout{1} = handles.output;



function In_dat_Callback(hObject, eventdata, handles)
% hObject    handle to In_dat (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of In_dat as text
%        str2double(get(hObject,'String')) returns contents of In_dat as a double


% --- Executes during object creation, after setting all properties.
function In_dat_CreateFcn(hObject, eventdata, handles)
% hObject    handle to In_dat (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function In_sco_Callback(hObject, eventdata, handles)
% hObject    handle to In_sco (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of In_sco as text
%        str2double(get(hObject,'String')) returns contents of In_sco as a double


% --- Executes during object creation, after setting all properties.
function In_sco_CreateFcn(hObject, eventdata, handles)
% hObject    handle to In_sco (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function In_out_Callback(hObject, eventdata, handles)
% hObject    handle to In_out (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of In_out as text
%        str2double(get(hObject,'String')) returns contents of In_out as a double


% --- Executes during object creation, after setting all properties.
function In_out_CreateFcn(hObject, eventdata, handles)
% hObject    handle to In_out (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end


% --- Executes on button press in pushbutton1.
function pushbutton1_Callback(hObject, eventdata, handles)
% hObject    handle to pushbutton1 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
d = uigetdir;
if ischar(d)
set(handles.In_dat,'string', d);
end
guidata(hObject, handles);


% --- Executes on button press in pushbutton2.
function pushbutton2_Callback(hObject, eventdata, handles)
% hObject    handle to pushbutton2 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
[n d]= uigetfile('*.txt');
if ischar(n)
set(handles.In_sco,'string', [d   n]);
end
guidata(hObject, handles);




function In_paral_Callback(hObject, eventdata, handles)
% hObject    handle to In_paral (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of In_paral as text
%        str2double(get(hObject,'String')) returns contents of In_paral as a double


% --- Executes during object creation, after setting all properties.
function In_paral_CreateFcn(hObject, eventdata, handles)
% hObject    handle to In_paral (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end


% --- Executes during object creation, after setting all properties.
function axes1_CreateFcn(hObject, eventdata, handles)
% hObject    handle to axes1 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: place code in OpeningFcn to populate axes1


% --- Executes on mouse press over axes background.
function axes1_ButtonDownFcn(hObject, eventdata, handles)
% hObject    handle to axes1 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
 

function my_imButtonDfcn(hObject, eventdata, handles)
web('http:neurospider.cn' ,'-browser')


% --- If Enable == 'on', executes on mouse press in 5 pixel border.
% --- Otherwise, executes on mouse press in 5 pixel border or over text6.
function text6_ButtonDownFcn(hObject, eventdata, handles)
% hObject    handle to text6 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
web('http:neurospider.cn' ,'-browser')



function In_cov_Callback(hObject, eventdata, handles)
% hObject    handle to In_cov (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of In_cov as text
%        str2double(get(hObject,'String')) returns contents of In_cov as a double


% --- Executes during object creation, after setting all properties.
function In_cov_CreateFcn(hObject, eventdata, handles)
% hObject    handle to In_cov (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end


% --- Executes on button press in pushbutton3.
function pushbutton3_Callback(hObject, eventdata, handles)
% hObject    handle to pushbutton3 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
[n d]= uigetfile('*.txt');
if ischar(n)
set(handles.In_cov,'string', [d   n]);
end
guidata(hObject, handles);

% --- Executes on button press in pushbutton4.



function In_thresh_Callback(hObject, eventdata, handles)
% hObject    handle to In_thresh (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of In_thresh as text
%        str2double(get(hObject,'String')) returns contents of In_thresh as a double


% --- Executes during object creation, after setting all properties.
function In_thresh_CreateFcn(hObject, eventdata, handles)
% hObject    handle to In_thresh (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



function In_kfold_Callback(hObject, eventdata, handles)
% hObject    handle to In_kfold (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of In_kfold as text
%        str2double(get(hObject,'String')) returns contents of In_kfold as a double


% --- Executes during object creation, after setting all properties.
function In_kfold_CreateFcn(hObject, eventdata, handles)
% hObject    handle to In_kfold (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end


% --- Executes on button press in CV_kf.
function CV_kf_Callback(hObject, eventdata, handles)
% hObject    handle to CV_kf (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

set(handles.In_kfold,'enable', 'on');

guidata(hObject, handles);

% Hint: get(hObject,'Value') returns toggle state of CV_kf


% --- Executes on button press in CV_lo.
function CV_lo_Callback(hObject, eventdata, handles)
% hObject    handle to CV_lo (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
set(handles.In_kfold,'enable', 'off');

guidata(hObject, handles);
% Hint: get(hObject,'Value') returns toggle state of CV_lo


% --- Executes on button press in checkbox1.
function checkbox1_Callback(hObject, eventdata, handles)
% hObject    handle to checkbox1 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
if get(hObject,'Value')
    set(handles.In_perm,'enable', 'on');
else
    set(handles.In_perm,'enable', 'off');
end
% Hint: get(hObject,'Value') returns toggle state of checkbox1



function In_perm_Callback(hObject, eventdata, handles)
% hObject    handle to In_perm (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of In_perm as text
%        str2double(get(hObject,'String')) returns contents of In_perm as a double


% --- Executes during object creation, after setting all properties.
function In_perm_CreateFcn(hObject, eventdata, handles)
% hObject    handle to In_perm (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end


% --- Executes on button press in checkbox2.
function checkbox2_Callback(hObject, eventdata, handles)
% hObject    handle to checkbox2 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hint: get(hObject,'Value') returns toggle state of checkbox2



function In_cvrp_Callback(hObject, eventdata, handles)
% hObject    handle to In_cvrp (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of In_cvrp as text
%        str2double(get(hObject,'String')) returns contents of In_cvrp as a double


% --- Executes during object creation, after setting all properties.
function In_cvrp_CreateFcn(hObject, eventdata, handles)
% hObject    handle to In_cvrp (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end


% --- Executes on selection change in pop_mtyp.
function pop_mtyp_Callback(hObject, eventdata, handles)
% hObject    handle to pop_mtyp (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: contents = cellstr(get(hObject,'String')) returns pop_mtyp contents as cell array
%        contents{get(hObject,'Value')} returns selected item from pop_mtyp


% --- Executes during object creation, after setting all properties.
function pop_mtyp_CreateFcn(hObject, eventdata, handles)
% hObject    handle to pop_mtyp (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: popupmenu controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end



% --- Executes on button press in pushbutton4.
function pushbutton4_Callback(hObject, eventdata, handles)
% hObject    handle to pushbutton4 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
d = uigetdir;
if ischar(d)
set(handles.In_out,'string', d);
end
guidata(hObject, handles);

% --- Executes on button press in pushbutton7.
function pushbutton7_Callback(hObject, eventdata, handles)
% hObject    handle to pushbutton7 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
[n, d]= uigetfile('*.mat');
[d n]
load([d n])

set(handles.In_dat,'string',CPMcfg.path.FC);
set(handles.In_sco,'string',CPMcfg.path.scores);
set(handles.In_cov,'string',CPMcfg.path.covar  );
set(handles.In_out,'string',CPMcfg.path.output );
set(handles.In_paral,'string',CPMcfg.paralle  );
set(handles.In_thresh,'string',num2str(CPMcfg.thresh)) ;
set(handles.In_kfold,'string',CPMcfg.kfold) ;
set(handles.In_cvrp,'string',CPMcfg.cvrp );
set(handles.CV_kf,'value',CPMcfg.isKfold ) ;
set(handles.CV_lo,'value',CPMcfg.isLOOCV  );
set(handles.checkbox1,'value',CPMcfg.isPermutation);
set(handles.In_perm,'string',CPMcfg.PermutationN );
set(handles.checkbox2,'value',CPMcfg.isExportConsesus);





% --- Executes on button press in button_run.
function button_run_Callback(hObject, eventdata, handles)
% hObject    handle to button_run (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

CPMcfg.path.FC = get(handles.In_dat,'string');
CPMcfg.path.scores = get(handles.In_sco,'string');
CPMcfg.path.covar = get(handles.In_cov,'string');
CPMcfg.path.output = get(handles.In_out,'string');
CPMcfg.paralle  =  str2double(get(handles.In_paral,'string'));
CPMcfg.thresh    =  str2num(get(handles.In_thresh,'string'));
CPMcfg.kfold    =  str2double(get(handles.In_kfold,'string'));
CPMcfg.cvrp     =  str2double(get(handles.In_cvrp,'string'));
CPMcfg.isKfold  =  get(handles.CV_kf,'value');
CPMcfg.isLOOCV  =  get(handles.CV_lo,'value');
CPMcfg.isPermutation = get(handles.checkbox1,'value');
CPMcfg.PermutationN  = str2double( get(handles.In_perm,'string'));
CPMcfg.isExportConsesus = get(handles.checkbox2,'value');


contents = cellstr(get(handles.pop_mtyp,'String'));
CPMcfg.modelType = contents{get(handles.pop_mtyp,'Value')};
CPMcfg.modelTypeIdx = get(handles.pop_mtyp,'Value');
CPMcfg.lassoAlpha   = 1;
save(sprintf('NS_CPM_AutoSaveParameter_%d_%d_%d_%d_%d_%.0f',clock),'CPMcfg')


% assignin('base','CPMcfg',CPMcfg)
hm = msgbox('Reading FC data... please waiting','modal');
set(hm,'Units','pixels');
figobj = get(handles.figure1);
set(hm,'Position' , figobj.Position);
CPMcfg.mainFigurePosition = figobj.Position;

Data= NS_CPM_prepare_data(CPMcfg);
assignin('base','Data',Data)
assignin('base','CPMcfg',CPMcfg)
close(hm)
hc= NS_CPM_confirm(Data,CPMcfg);
set(hObject,'backgroundcolor',[0.8 0 0])
drawnow
uiwait(hc)


ALLPerformance = evalin('base','ALLPerformance');
msg = guiReport(ALLPerformance,CPMcfg);
set(handles.TextReport1,'string',msg.predict);
if CPMcfg.isPermutation==1
    set(handles.TextReport2,'string',msg.permu);
end
set(hObject,'backgroundcolor',[0.94 0.94 0.94])
drawnow

 
function msg = guiReport(ALLPerformance,CPMcfg)

msg.predict ='';
msg.permu  ='';
for i = 1:length(ALLPerformance)
    Performance = ALLPerformance{i};    
    if isnan(Performance.positive.r),Performance.positive.r=-9.9;Performance.positive.p=-9.9;end
    if isnan(Performance.negative.p),Performance.negative.r=-9.9;Performance.negative.p=-9.9;end
    
    msg.predict(end+1,:) = sprintf(' positive (%.4f): r=% 2.3f ; p=% 2.3f',CPMcfg.thresh(i), Performance.positive.r,Performance.positive.p);
    msg.predict(end+1,:) = sprintf(' negative (%.4f): r=% 2.3f ; p=% 2.3f',CPMcfg.thresh(i),Performance.negative.r,Performance.negative.p);
    
    if CPMcfg.isPermutation==1
        if isempty(Performance.Permutation.p_positive),Performance.Permutation.p_positive=-9.9;end
        if isempty(Performance.Permutation.p_negative),Performance.Permutation.p_negative=-9.9;end
        msg.permu(end+1,:) = sprintf(' positive (%.4f): p=% 2.3f',CPMcfg.thresh(i), Performance.Permutation.p_positive);
        msg.permu(end+1,:) = sprintf(' negative (%.4f): p=% 2.3f',CPMcfg.thresh(i), Performance.Permutation.p_negative);
    end
end

 


% --- Creates and returns a handle to the GUI figure. 
function h1 = NS_CPM_LayoutFcn(policy)
% policy - create a new figure or use a singleton. 'new' or 'reuse'.

persistent hsingleton;
if strcmpi(policy, 'reuse') & ishandle(hsingleton)
    h1 = hsingleton;
    return;
end

appdata = [];
appdata.GUIDEOptions = struct(...
    'active_h', [], ...
    'taginfo', struct(...
    'figure', 2, ...
    'text', 23, ...
    'edit', 11, ...
    'pushbutton', 8, ...
    'uipanel', 14, ...
    'axes', 3, ...
    'uibuttongroup', 4, ...
    'radiobutton', 4, ...
    'checkbox', 3, ...
    'popupmenu', 2), ...
    'override', 1, ...
    'release', [], ...
    'resize', 'simple', ...
    'accessibility', 'callback', ...
    'mfile', 1, ...
    'callbacks', 1, ...
    'singleton', 1, ...
    'syscolorfig', 1, ...
    'blocking', 0, ...
    'lastSavedFile', '/home/xiao/MyToolBox_XIAO_TBX/NS_CPM/functions/NS_CPM.m', ...
    'lastFilename', '/home/xiao/MyToolBox_XIAO_TBX/NS_CPM/NS_CPM.fig');
appdata.lastValidTag = 'figure1';
appdata.GUIDELayoutEditor = [];
appdata.initTags = struct(...
    'handle', [], ...
    'tag', 'figure1');

h1 = figure(...
'PaperUnits','centimeters',...
'Units',get(0,'defaultfigureUnits'),...
'Position',[951.6 405.571428571428 626 808],...
'Visible',get(0,'defaultfigureVisible'),...
'Color',get(0,'defaultfigureColor'),...
'CurrentAxesMode','manual',...
'IntegerHandle','off',...
'Colormap',get(0,'defaultfigureColormap'),...
'MenuBar','none',...
'ToolBar',get(0,'defaultfigureToolBar'),...
'ToolBarMode',get(0,'defaultfigureToolBarMode'),...
'Pointer',get(0,'defaultfigurePointer'),...
'Name','NS_CPM 1.0.31_beta',...
'NumberTitle','off',...
'HandleVisibility','callback',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)NS_CPM('figure1_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','figure1',...
'Resize',get(0,'defaultfigureResize'),...
'PaperPosition',[0.635 6.35 20.32 15.24],...
'PaperSize',[20.99999864 29.69999902],...
'PaperSizeMode',get(0,'defaultfigurePaperSizeMode'),...
'PaperType','A4',...
'ScreenPixelsPerInchMode','manual');

appdata = [];
appdata.lastValidTag = 'uipanel8';

h2 = uipanel(...
'Parent',h1,...
'FontUnits',get(0,'defaultuipanelFontUnits'),...
'Units',get(0,'defaultuipanelUnits'),...
'Title',blanks(0),...
'Tag','uipanel8',...
'Position',[0.0324786324786325 0.00436681222707424 0.938461538461538 0.0625909752547307],...
'Layout',[],...
'FontSize',8,...
'FontSizeMode',get(0,'defaultuipanelFontSizeMode'),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text5';

h3 = uicontrol(...
'Parent',h2,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment','right',...
'String','Parallel workers：',...
'Style','text',...
'Position',[0.0359801478451659 0.365711601690935 0.219307567818154 0.365711601690935],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text5',...
'FontSize',get(0,'defaultuicontrolFontSize'));

appdata = [];
appdata.lastValidTag = 'In_paral';

h4 = uicontrol(...
'Parent',h2,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','0',...
'Style','edit',...
'Position',[0.248434354169003 0.279661813057774 0.0582535727016972 0.537811178957257],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)NS_CPM('In_paral_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)NS_CPM('In_paral_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','In_paral',...
'FontSize',8,...
'FontSizeMode',get(0,'defaultuicontrolFontSizeMode'));

appdata = [];
appdata.lastValidTag = 'button_run';

h5 = uicontrol(...
'Parent',h2,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','RUN',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[0.851530165668926 0.0844966484226062 0.104513762788339 0.781593997909107],...
'Callback',@(hObject,eventdata)NS_CPM('button_run_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'Tag','button_run',...
'FontSize',14);

appdata = [];
appdata.lastValidTag = 'pushbutton7';

h6 = uicontrol(...
'Parent',h2,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','Load',...
'Style',get(0,'defaultuicontrolStyle'),...
'Position',[0.700756212793946 0.105620810528258 0.099373741667601 0.718221511592153],...
'Callback',@(hObject,eventdata)NS_CPM('pushbutton7_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton7',...
'KeyPressFcn',blanks(0),...
'FontSize',14);

appdata = [];
appdata.lastValidTag = 'uipanel2';

h7 = uipanel(...
'Parent',h1,...
'FontUnits',get(0,'defaultuipanelFontUnits'),...
'Units',get(0,'defaultuipanelUnits'),...
'Title',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'Tag','uipanel2',...
'Position',[0.0278745644599303 0.799525504151839 0.930313588850174 0.182680901542112],...
'Layout',[],...
'FontSize',8,...
'FontSizeMode',get(0,'defaultuipanelFontSizeMode'));

appdata = [];
appdata.lastValidTag = 'axes1';

h8 = axes(...
'Parent',h7,...
'FontUnits',get(0,'defaultaxesFontUnits'),...
'Units',get(0,'defaultaxesUnits'),...
'CameraPosition',[0.5 0.5 9.16025403784439],...
'CameraPositionMode',get(0,'defaultaxesCameraPositionMode'),...
'CameraTarget',[0.5 0.5 0.5],...
'CameraTargetMode',get(0,'defaultaxesCameraTargetMode'),...
'CameraViewAngle',6.60861036031192,...
'CameraViewAngleMode',get(0,'defaultaxesCameraViewAngleMode'),...
'PlotBoxAspectRatio',[1 0.863309352517986 0.863309352517986],...
'PlotBoxAspectRatioMode',get(0,'defaultaxesPlotBoxAspectRatioMode'),...
'Colormap',[0.2422 0.1504 0.6603;0.2444 0.1534 0.6728;0.2464 0.1569 0.6847;0.2484 0.1607 0.6961;0.2503 0.1648 0.7071;0.2522 0.1689 0.7179;0.254 0.1732 0.7286;0.2558 0.1773 0.7393;0.2576 0.1814 0.7501;0.2594 0.1854 0.761;0.2611 0.1893 0.7719;0.2628 0.1932 0.7828;0.2645 0.1972 0.7937;0.2661 0.2011 0.8043;0.2676 0.2052 0.8148;0.2691 0.2094 0.8249;0.2704 0.2138 0.8346;0.2717 0.2184 0.8439;0.2729 0.2231 0.8528;0.274 0.228 0.8612;0.2749 0.233 0.8692;0.2758 0.2382 0.8767;0.2766 0.2435 0.884;0.2774 0.2489 0.8908;0.2781 0.2543 0.8973;0.2788 0.2598 0.9035;0.2794 0.2653 0.9094;0.2798 0.2708 0.915;0.2802 0.2764 0.9204;0.2806 0.2819 0.9255;0.2809 0.2875 0.9305;0.2811 0.293 0.9352;0.2813 0.2985 0.9397;0.2814 0.304 0.9441;0.2814 0.3095 0.9483;0.2813 0.315 0.9524;0.2811 0.3204 0.9563;0.2809 0.3259 0.96;0.2807 0.3313 0.9636;0.2803 0.3367 0.967;0.2798 0.3421 0.9702;0.2791 0.3475 0.9733;0.2784 0.3529 0.9763;0.2776 0.3583 0.9791;0.2766 0.3638 0.9817;0.2754 0.3693 0.984;0.2741 0.3748 0.9862;0.2726 0.3804 0.9881;0.271 0.386 0.9898;0.2691 0.3916 0.9912;0.267 0.3973 0.9924;0.2647 0.403 0.9935;0.2621 0.4088 0.9946;0.2591 0.4145 0.9955;0.2556 0.4203 0.9965;0.2517 0.4261 0.9974;0.2473 0.4319 0.9983;0.2424 0.4378 0.9991;0.2369 0.4437 0.9996;0.2311 0.4497 0.9995;0.225 0.4559 0.9985;0.2189 0.462 0.9968;0.2128 0.4682 0.9948;0.2066 0.4743 0.9926;0.2006 0.4803 0.9906;0.195 0.4861 0.9887;0.1903 0.4919 0.9867;0.1869 0.4975 0.9844;0.1847 0.503 0.9819;0.1831 0.5084 0.9793;0.1818 0.5138 0.9766;0.1806 0.5191 0.9738;0.1795 0.5244 0.9709;0.1785 0.5296 0.9677;0.1778 0.5349 0.9641;0.1773 0.5401 0.9602;0.1768 0.5452 0.956;0.1764 0.5504 0.9516;0.1755 0.5554 0.9473;0.174 0.5605 0.9432;0.1716 0.5655 0.9393;0.1686 0.5705 0.9357;0.1649 0.5755 0.9323;0.161 0.5805 0.9289;0.1573 0.5854 0.9254;0.154 0.5902 0.9218;0.1513 0.595 0.9182;0.1492 0.5997 0.9147;0.1475 0.6043 0.9113;0.1461 0.6089 0.908;0.1446 0.6135 0.905;0.1429 0.618 0.9022;0.1408 0.6226 0.8998;0.1383 0.6272 0.8975;0.1354 0.6317 0.8953;0.1321 0.6363 0.8932;0.1288 0.6408 0.891;0.1253 0.6453 0.8887;0.1219 0.6497 0.8862;0.1185 0.6541 0.8834;0.1152 0.6584 0.8804;0.1119 0.6627 0.877;0.1085 0.6669 0.8734;0.1048 0.671 0.8695;0.1009 0.675 0.8653;0.0964 0.6789 0.8609;0.0914 0.6828 0.8562;0.0855 0.6865 0.8513;0.0789 0.6902 0.8462;0.0713 0.6938 0.8409;0.0628 0.6972 0.8355;0.0535 0.7006 0.8299;0.0433 0.7039 0.8242;0.0328 0.7071 0.8183;0.0234 0.7103 0.8124;0.0155 0.7133 0.8064;0.0091 0.7163 0.8003;0.0046 0.7192 0.7941;0.0019 0.722 0.7878;0.0009 0.7248 0.7815;0.0018 0.7275 0.7752;0.0046 0.7301 0.7688;0.0094 0.7327 0.7623;0.0162 0.7352 0.7558;0.0253 0.7376 0.7492;0.0369 0.74 0.7426;0.0504 0.7423 0.7359;0.0638 0.7446 0.7292;0.077 0.7468 0.7224;0.0899 0.7489 0.7156;0.1023 0.751 0.7088;0.1141 0.7531 0.7019;0.1252 0.7552 0.695;0.1354 0.7572 0.6881;0.1448 0.7593 0.6812;0.1532 0.7614 0.6741;0.1609 0.7635 0.6671;0.1678 0.7656 0.6599;0.1741 0.7678 0.6527;0.1799 0.7699 0.6454;0.1853 0.7721 0.6379;0.1905 0.7743 0.6303;0.1954 0.7765 0.6225;0.2003 0.7787 0.6146;0.2061 0.7808 0.6065;0.2118 0.7828 0.5983;0.2178 0.7849 0.5899;0.2244 0.7869 0.5813;0.2318 0.7887 0.5725;0.2401 0.7905 0.5636;0.2491 0.7922 0.5546;0.2589 0.7937 0.5454;0.2695 0.7951 0.536;0.2809 0.7964 0.5266;0.2929 0.7975 0.517;0.3052 0.7985 0.5074;0.3176 0.7994 0.4975;0.3301 0.8002 0.4876;0.3424 0.8009 0.4774;0.3548 0.8016 0.4669;0.3671 0.8021 0.4563;0.3795 0.8026 0.4454;0.3921 0.8029 0.4344;0.405 0.8031 0.4233;0.4184 0.803 0.4122;0.4322 0.8028 0.4013;0.4463 0.8024 0.3904;0.4608 0.8018 0.3797;0.4753 0.8011 0.3691;0.4899 0.8002 0.3586;0.5044 0.7993 0.348;0.5187 0.7982 0.3374;0.5329 0.797 0.3267;0.547 0.7957 0.3159;0.5609 0.7943 0.305;0.5748 0.7929 0.2941;0.5886 0.7913 0.2833;0.6024 0.7896 0.2726;0.6161 0.7878 0.2622;0.6297 0.7859 0.2521;0.6433 0.7839 0.2423;0.6567 0.7818 0.2329;0.6701 0.7796 0.2239;0.6833 0.7773 0.2155;0.6963 0.775 0.2075;0.7091 0.7727 0.1998;0.7218 0.7703 0.1924;0.7344 0.7679 0.1852;0.7468 0.7654 0.1782;0.759 0.7629 0.1717;0.771 0.7604 0.1658;0.7829 0.7579 0.1608;0.7945 0.7554 0.157;0.806 0.7529 0.1546;0.8172 0.7505 0.1535;0.8281 0.7481 0.1536;0.8389 0.7457 0.1546;0.8495 0.7435 0.1564;0.86 0.7413 0.1587;0.8703 0.7392 0.1615;0.8804 0.7372 0.165;0.8903 0.7353 0.1695;0.9 0.7336 0.1749;0.9093 0.7321 0.1815;0.9184 0.7308 0.189;0.9272 0.7298 0.1973;0.9357 0.729 0.2061;0.944 0.7285 0.2151;0.9523 0.7284 0.2237;0.9606 0.7285 0.2312;0.9689 0.7292 0.2373;0.977 0.7304 0.2418;0.9842 0.733 0.2446;0.99 0.7365 0.2429;0.9946 0.7407 0.2394;0.9966 0.7458 0.2351;0.9971 0.7513 0.2309;0.9972 0.7569 0.2267;0.9971 0.7626 0.2224;0.9969 0.7683 0.2181;0.9966 0.774 0.2138;0.9962 0.7798 0.2095;0.9957 0.7856 0.2053;0.9949 0.7915 0.2012;0.9938 0.7974 0.1974;0.9923 0.8034 0.1939;0.9906 0.8095 0.1906;0.9885 0.8156 0.1875;0.9861 0.8218 0.1846;0.9835 0.828 0.1817;0.9807 0.8342 0.1787;0.9778 0.8404 0.1757;0.9748 0.8467 0.1726;0.972 0.8529 0.1695;0.9694 0.8591 0.1665;0.9671 0.8654 0.1636;0.9651 0.8716 0.1608;0.9634 0.8778 0.1582;0.9619 0.884 0.1557;0.9608 0.8902 0.1532;0.9601 0.8963 0.1507;0.9596 0.9023 0.148;0.9595 0.9084 0.145;0.9597 0.9143 0.1418;0.9601 0.9203 0.1382;0.9608 0.9262 0.1344;0.9618 0.932 0.1304;0.9629 0.9379 0.1261;0.9642 0.9437 0.1216;0.9657 0.9494 0.1168;0.9674 0.9552 0.1116;0.9692 0.9609 0.1061;0.9711 0.9667 0.1001;0.973 0.9724 0.0938;0.9749 0.9782 0.0872;0.9769 0.9839 0.0805],...
'ColormapMode',get(0,'defaultaxesColormapMode'),...
'Alphamap',[0 0.0159 0.0317 0.0476 0.0635 0.0794 0.0952 0.1111 0.127 0.1429 0.1587 0.1746 0.1905 0.2063 0.2222 0.2381 0.254 0.2698 0.2857 0.3016 0.3175 0.3333 0.3492 0.3651 0.381 0.3968 0.4127 0.4286 0.4444 0.4603 0.4762 0.4921 0.5079 0.5238 0.5397 0.5556 0.5714 0.5873 0.6032 0.619 0.6349 0.6508 0.6667 0.6825 0.6984 0.7143 0.7302 0.746 0.7619 0.7778 0.7937 0.8095 0.8254 0.8413 0.8571 0.873 0.8889 0.9048 0.9206 0.9365 0.9524 0.9683 0.9841 1],...
'AlphamapMode',get(0,'defaultaxesAlphamapMode'),...
'XTick',[0 0.5 1],...
'XTickMode',get(0,'defaultaxesXTickMode'),...
'XTickLabel',{  '0'; '0.5'; '1' },...
'XTickLabelMode',get(0,'defaultaxesXTickLabelMode'),...
'YTick',[0 0.5 1],...
'YTickMode',get(0,'defaultaxesYTickMode'),...
'YTickLabel',{  '0'; '0.5'; '1' },...
'YTickLabelMode',get(0,'defaultaxesYTickLabelMode'),...
'CameraMode',get(0,'defaultaxesCameraMode'),...
'DataSpaceMode',get(0,'defaultaxesDataSpaceMode'),...
'ColorSpaceMode',get(0,'defaultaxesColorSpaceMode'),...
'DecorationContainerMode',get(0,'defaultaxesDecorationContainerMode'),...
'ChildContainerMode',get(0,'defaultaxesChildContainerMode'),...
'XRulerMode',get(0,'defaultaxesXRulerMode'),...
'YRulerMode',get(0,'defaultaxesYRulerMode'),...
'ZRulerMode',get(0,'defaultaxesZRulerMode'),...
'AmbientLightSourceMode',get(0,'defaultaxesAmbientLightSourceMode'),...
'Position',[0.0396975425330813 0.13013698630137 0.24007561436673 0.835616438356164],...
'InnerPosition',[0.0396975425330813 0.13013698630137 0.24007561436673 0.835616438356164],...
'InnerPositionMode',get(0,'defaultaxesInnerPositionMode'),...
'ActivePositionProperty','position',...
'ActivePositionPropertyMode',get(0,'defaultaxesActivePositionPropertyMode'),...
'PositionConstraint','innerposition',...
'PositionConstraintMode',get(0,'defaultaxesPositionConstraintMode'),...
'LooseInset',[0.277654233068484 0.0458885741334728 0.202901170319277 0.0312876641819133],...
'LooseInsetMode',get(0,'defaultaxesLooseInsetMode'),...
'ColorOrder',get(0,'defaultaxesColorOrder'),...
'FontSize',8.5,...
'FontSizeMode',get(0,'defaultaxesFontSizeMode'),...
'SortMethod','childorder',...
'SortMethodMode',get(0,'defaultaxesSortMethodMode'),...
'Layout',[],...
'ButtonDownFcn',@(hObject,eventdata)NS_CPM('axes1_ButtonDownFcn',hObject,eventdata,guidata(hObject)),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)NS_CPM('axes1_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','axes1');

h9 = get(h8,'title');

set(h9,...
'Parent',h8,...
'Units','data',...
'FontUnits','points',...
'DecorationContainer',[],...
'DecorationContainerMode','auto',...
'Color',[0 0 0],...
'ColorMode','auto',...
'Position',[0.500000641500349 1.01947916666667 0.500000000000007],...
'PositionMode','auto',...
'Interpreter','tex',...
'InterpreterMode','auto',...
'Rotation',0,...
'RotationMode','auto',...
'FontName','Helvetica',...
'FontNameMode','auto',...
'FontSize',9.35,...
'FontSizeMode','auto',...
'FontAngle','normal',...
'FontAngleMode','auto',...
'FontWeight','bold',...
'FontWeightMode','auto',...
'HorizontalAlignment','center',...
'HorizontalAlignmentMode','auto',...
'VerticalAlignment','bottom',...
'VerticalAlignmentMode','auto',...
'EdgeColor','none',...
'EdgeColorMode','auto',...
'LineStyle','-',...
'LineStyleMode','auto',...
'LineWidth',0.5,...
'LineWidthMode','auto',...
'BackgroundColor','none',...
'BackgroundColorMode','auto',...
'Margin',3,...
'MarginMode','auto',...
'Clipping','off',...
'ClippingMode','auto',...
'Layer','middle',...
'LayerMode','auto',...
'FontSmoothing','on',...
'FontSmoothingMode','auto',...
'IncludeRenderer','on',...
'IsContainer','off',...
'IsContainerMode','auto',...
'DimensionNames',{  'X' 'Y' 'Z' },...
'DimensionNamesMode','auto',...
'XLimInclude','on',...
'XLimIncludeMode','auto',...
'YLimInclude','on',...
'YLimIncludeMode','auto',...
'ZLimInclude','on',...
'ZLimIncludeMode','auto',...
'CLimInclude','on',...
'CLimIncludeMode','auto',...
'ALimInclude','on',...
'ALimIncludeMode','auto',...
'Description','Axes Title',...
'DescriptionMode','auto',...
'Visible','on',...
'VisibleMode','auto',...
'Serializable','on',...
'SerializableMode','auto',...
'HandleVisibility','off',...
'HandleVisibilityMode','auto',...
'TransformForPrintFcnImplicitInvoke','on',...
'TransformForPrintFcnImplicitInvokeMode','auto',...
'HG1EraseMode','auto',...
'BusyAction','queue',...
'Interruptible','on',...
'HitTest','on',...
'HitTestMode','auto',...
'PickableParts','visible',...
'PickablePartsMode','auto');

h10 = get(h8,'xlabel');

set(h10,...
'Parent',h8,...
'Units','data',...
'FontUnits','points',...
'DecorationContainer',[],...
'DecorationContainerMode','auto',...
'Color',[0.15 0.15 0.15],...
'ColorMode','auto',...
'Position',[0.500000476837158 -0.143888885411951 7.105427357601e-15],...
'PositionMode','auto',...
'Interpreter','tex',...
'InterpreterMode','auto',...
'Rotation',0,...
'RotationMode','auto',...
'FontName','Helvetica',...
'FontNameMode','auto',...
'FontSize',9.35,...
'FontSizeMode','auto',...
'FontAngle','normal',...
'FontAngleMode','auto',...
'FontWeight','normal',...
'FontWeightMode','auto',...
'HorizontalAlignment','center',...
'HorizontalAlignmentMode','auto',...
'VerticalAlignment','top',...
'VerticalAlignmentMode','auto',...
'EdgeColor','none',...
'EdgeColorMode','auto',...
'LineStyle','-',...
'LineStyleMode','auto',...
'LineWidth',0.5,...
'LineWidthMode','auto',...
'BackgroundColor','none',...
'BackgroundColorMode','auto',...
'Margin',3,...
'MarginMode','auto',...
'Clipping','off',...
'ClippingMode','auto',...
'Layer','back',...
'LayerMode','auto',...
'FontSmoothing','on',...
'FontSmoothingMode','auto',...
'IncludeRenderer','on',...
'IsContainer','off',...
'IsContainerMode','auto',...
'DimensionNames',{  'X' 'Y' 'Z' },...
'DimensionNamesMode','auto',...
'XLimInclude','on',...
'XLimIncludeMode','auto',...
'YLimInclude','on',...
'YLimIncludeMode','auto',...
'ZLimInclude','on',...
'ZLimIncludeMode','auto',...
'CLimInclude','on',...
'CLimIncludeMode','auto',...
'ALimInclude','on',...
'ALimIncludeMode','auto',...
'Description','AxisRulerBase Label',...
'DescriptionMode','auto',...
'Visible','on',...
'VisibleMode','auto',...
'Serializable','on',...
'SerializableMode','auto',...
'HandleVisibility','off',...
'HandleVisibilityMode','auto',...
'TransformForPrintFcnImplicitInvoke','on',...
'TransformForPrintFcnImplicitInvokeMode','auto',...
'HG1EraseMode','auto',...
'BusyAction','queue',...
'Interruptible','on',...
'HitTest','on',...
'HitTestMode','auto',...
'PickableParts','visible',...
'PickablePartsMode','auto');

h11 = get(h8,'ylabel');

set(h11,...
'Parent',h8,...
'Units','data',...
'FontUnits','points',...
'DecorationContainer',[],...
'DecorationContainerMode','auto',...
'Color',[0.15 0.15 0.15],...
'ColorMode','auto',...
'Position',[-0.164988005733033 0.500000476837158 7.105427357601e-15],...
'PositionMode','auto',...
'Interpreter','tex',...
'InterpreterMode','auto',...
'Rotation',90,...
'RotationMode','auto',...
'FontName','Helvetica',...
'FontNameMode','auto',...
'FontSize',9.35,...
'FontSizeMode','auto',...
'FontAngle','normal',...
'FontAngleMode','auto',...
'FontWeight','normal',...
'FontWeightMode','auto',...
'HorizontalAlignment','center',...
'HorizontalAlignmentMode','auto',...
'VerticalAlignment','bottom',...
'VerticalAlignmentMode','auto',...
'EdgeColor','none',...
'EdgeColorMode','auto',...
'LineStyle','-',...
'LineStyleMode','auto',...
'LineWidth',0.5,...
'LineWidthMode','auto',...
'BackgroundColor','none',...
'BackgroundColorMode','auto',...
'Margin',3,...
'MarginMode','auto',...
'Clipping','off',...
'ClippingMode','auto',...
'Layer','back',...
'LayerMode','auto',...
'FontSmoothing','on',...
'FontSmoothingMode','auto',...
'IncludeRenderer','on',...
'IsContainer','off',...
'IsContainerMode','auto',...
'DimensionNames',{  'X' 'Y' 'Z' },...
'DimensionNamesMode','auto',...
'XLimInclude','on',...
'XLimIncludeMode','auto',...
'YLimInclude','on',...
'YLimIncludeMode','auto',...
'ZLimInclude','on',...
'ZLimIncludeMode','auto',...
'CLimInclude','on',...
'CLimIncludeMode','auto',...
'ALimInclude','on',...
'ALimIncludeMode','auto',...
'Description','AxisRulerBase Label',...
'DescriptionMode','auto',...
'Visible','on',...
'VisibleMode','auto',...
'Serializable','on',...
'SerializableMode','auto',...
'HandleVisibility','off',...
'HandleVisibilityMode','auto',...
'TransformForPrintFcnImplicitInvoke','on',...
'TransformForPrintFcnImplicitInvokeMode','auto',...
'HG1EraseMode','auto',...
'BusyAction','queue',...
'Interruptible','on',...
'HitTest','on',...
'HitTestMode','auto',...
'PickableParts','visible',...
'PickablePartsMode','auto');

h12 = get(h8,'zlabel');

set(h12,...
'Parent',h8,...
'Units','data',...
'FontUnits','points',...
'DecorationContainer',[],...
'DecorationContainerMode','auto',...
'Color',[0.15 0.15 0.15],...
'ColorMode','auto',...
'Position',[0 0 0],...
'PositionMode','auto',...
'Interpreter','tex',...
'InterpreterMode','auto',...
'Rotation',0,...
'RotationMode','auto',...
'FontName','Helvetica',...
'FontNameMode','auto',...
'FontSize',10,...
'FontSizeMode','auto',...
'FontAngle','normal',...
'FontAngleMode','auto',...
'FontWeight','normal',...
'FontWeightMode','auto',...
'HorizontalAlignment','left',...
'HorizontalAlignmentMode','auto',...
'VerticalAlignment','middle',...
'VerticalAlignmentMode','auto',...
'EdgeColor','none',...
'EdgeColorMode','auto',...
'LineStyle','-',...
'LineStyleMode','auto',...
'LineWidth',0.5,...
'LineWidthMode','auto',...
'BackgroundColor','none',...
'BackgroundColorMode','auto',...
'Margin',3,...
'MarginMode','auto',...
'Clipping','off',...
'ClippingMode','auto',...
'Layer','middle',...
'LayerMode','auto',...
'FontSmoothing','on',...
'FontSmoothingMode','auto',...
'IncludeRenderer','on',...
'IsContainer','off',...
'IsContainerMode','auto',...
'DimensionNames',{  'X' 'Y' 'Z' },...
'DimensionNamesMode','auto',...
'XLimInclude','on',...
'XLimIncludeMode','auto',...
'YLimInclude','on',...
'YLimIncludeMode','auto',...
'ZLimInclude','on',...
'ZLimIncludeMode','auto',...
'CLimInclude','on',...
'CLimIncludeMode','auto',...
'ALimInclude','on',...
'ALimIncludeMode','auto',...
'Description','AxisRulerBase Label',...
'DescriptionMode','auto',...
'Visible','off',...
'VisibleMode','auto',...
'Serializable','on',...
'SerializableMode','auto',...
'HandleVisibility','off',...
'HandleVisibilityMode','auto',...
'TransformForPrintFcnImplicitInvoke','on',...
'TransformForPrintFcnImplicitInvokeMode','auto',...
'HG1EraseMode','auto',...
'BusyAction','queue',...
'Interruptible','on',...
'HitTest','on',...
'HitTestMode','auto',...
'PickableParts','visible',...
'PickablePartsMode','auto');

appdata = [];
appdata.lastValidTag = 'text7';

h13 = uicontrol(...
'Parent',h7,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment','left',...
'String','NS_CPM ',...
'Style','text',...
'Position',[0.34374575540503 0.634201022561272 0.348927852220182 0.348462100308391],...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text7',...
'FontSize',28);

appdata = [];
appdata.lastValidTag = 'text6';

h14 = uicontrol(...
'Parent',h7,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment','left',...
'String','Neural signature - connectome prediction model',...
'Style','text',...
'Position',[0.34374575540503 0.411185278363902 0.592486402532288 0.16029256614186],...
'Callback','%automatic',...
'Children',[],...
'Tooltip','Right click to access',...
'TooltipMode',get(0,'defaultuicontrolTooltipMode'),...
'ForegroundColor',[0.0784313725490196 0.168627450980392 0.549019607843137],...
'Enable',get(0,'defaultuicontrolEnable'),...
'TooltipString','Right click to access',...
'ButtonDownFcn',@(hObject,eventdata)NS_CPM('text6_ButtonDownFcn',hObject,eventdata,guidata(hObject)),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'Tag','text6',...
'KeyPressFcn','%automatic',...
'FontSize',9);

appdata = [];
appdata.lastValidTag = 'text20';

h15 = uicontrol(...
'Parent',h7,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','Beta',...
'Style','text',...
'Position',[0.635670542658548 0.696924200616783 0.152008173244435 0.22301574419737],...
'Children',[],...
'ForegroundColor',[0 0.4 0.8],...
'Tag','text20',...
'FontSize',20,...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'text22';

h16 = uicontrol(...
'Parent',h7,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment','left',...
'String',{  'he-lab.cn'; 'NeuroSpider.cn'; blanks(0) },...
'Style','text',...
'Position',[0.34374575540503 0.0627231780555104 0.374838336295937 0.355431342314559],...
'Children',[],...
'Tag','text22',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'uipanel4';

h17 = uipanel(...
'Parent',h1,...
'FontUnits',get(0,'defaultuipanelFontUnits'),...
'Units',get(0,'defaultuipanelUnits'),...
'Title','Model',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'Tag','uipanel4',...
'Position',[0.0291595197255575 0.667202572347267 0.92967409948542 0.107717041800643],...
'Layout',[],...
'FontSize',get(0,'defaultuipanelFontSize'));

appdata = [];
appdata.lastValidTag = 'text10';

h18 = uicontrol(...
'Parent',h17,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment','right',...
'String','Feature selection thresholds:',...
'Style','text',...
'Position',[0.0204462300021522 0.419490477368291 0.340150917308533 0.489405556929673],...
'Children',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'Tag','text10',...
'FontSize',get(0,'defaultuicontrolFontSize'));

appdata = [];
appdata.lastValidTag = 'In_thresh';

h19 = uicontrol(...
'Parent',h17,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','0.05',...
'Style','edit',...
'Position',[0.377325880948809 0.541841866600709 0.193309810929439 0.402011707477945],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)NS_CPM('In_thresh_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)NS_CPM('In_thresh_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','In_thresh',...
'FontSize',8,...
'FontSizeMode',get(0,'defaultuicontrolFontSizeMode'));

appdata = [];
appdata.lastValidTag = 'text13';

h20 = uicontrol(...
'Parent',h17,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment','left',...
'String','Tips:  number or vector',...
'Style','text',...
'Position',[0.596654275092937 0.592592592592593 0.37360594795539 0.259259259259259],...
'Children',[],...
'Tag','text13',...
'FontSize',8,...
'FontSizeMode',get(0,'defaultuicontrolFontSizeMode'),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'pop_mtyp';

h21 = uicontrol(...
'Parent',h17,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String',{  'CPM (y = mx + b)'; 'LASSO' },...
'Style','popupmenu',...
'Value',1,...
'ValueMode',get(0,'defaultuicontrolValueMode'),...
'Position',[0.377777777777778 0.129032258064516 0.218518518518519 0.338709677419355],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)NS_CPM('pop_mtyp_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)NS_CPM('pop_mtyp_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','pop_mtyp',...
'FontSize',8,...
'FontSizeMode',get(0,'defaultuicontrolFontSizeMode'));

appdata = [];
appdata.lastValidTag = 'text16';

h22 = uicontrol(...
'Parent',h17,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment','right',...
'String','Model type:',...
'Style','text',...
'Position',[0.0166666666666667 0.145161290322581 0.340740740740741 0.32258064516129],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text16',...
'FontSize',get(0,'defaultuicontrolFontSize'));

appdata = [];
appdata.lastValidTag = 'uipanel5';

h23 = uipanel(...
'Parent',h1,...
'FontUnits',get(0,'defaultuipanelFontUnits'),...
'Units',get(0,'defaultuipanelUnits'),...
'Title','Validation',...
'ResizeFcn',blanks(0),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','uipanel5',...
'Position',[0.0274442538593482 0.45016077170418 0.93138936535163 0.213826366559486],...
'Layout',[],...
'FontSize',get(0,'defaultuipanelFontSize'));

appdata = [];
appdata.lastValidTag = 'uibuttongroup3';

h24 = uibuttongroup(...
'Parent',h23,...
'FontUnits','points',...
'Units','normalized',...
'Title','CV mothods:',...
'Tag','uibuttongroup3',...
'Position',[0.0406654343807763 0.0671641791044776 0.33641404805915 0.873134328358209],...
'Layout',[],...
'FontSize',8,...
'FontSizeMode','auto',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'CV_kf';

h25 = uicontrol(...
'Parent',h24,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','K-FOLD',...
'Style','radiobutton',...
'Value',1,...
'Position',[0.107344632768362 0.51948051948052 0.514124293785311 0.363636363636364],...
'Callback',@(hObject,eventdata)NS_CPM('CV_kf_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'Tag','CV_kf',...
'FontSize',8,...
'FontSizeMode',get(0,'defaultuicontrolFontSizeMode'),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'CV_lo';

h26 = uicontrol(...
'Parent',h24,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','LOOCV',...
'Style','radiobutton',...
'Position',[0.106741573033708 0.394230769230769 0.51685393258427 0.240384615384615],...
'Callback',@(hObject,eventdata)NS_CPM('CV_lo_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'Enable','off',...
'Visible','off',...
'Tag','CV_lo',...
'FontSize',8,...
'FontSizeMode',get(0,'defaultuicontrolFontSizeMode'),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'In_kfold';

h27 = uicontrol(...
'Parent',h24,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','10',...
'Style','edit',...
'Position',[0.522471910112359 0.596153846153846 0.264044943820225 0.221153846153846],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)NS_CPM('In_kfold_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)NS_CPM('In_kfold_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','In_kfold',...
'FontSize',8,...
'FontSizeMode',get(0,'defaultuicontrolFontSizeMode'));

appdata = [];
appdata.lastValidTag = 'In_cvrp';

h28 = uicontrol(...
'Parent',h24,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','20',...
'Style','edit',...
'Position',[0.528089887640449 0.0576923076923077 0.258426966292135 0.221153846153846],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)NS_CPM('In_cvrp_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)NS_CPM('In_cvrp_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','In_cvrp',...
'FontSize',8,...
'FontSizeMode',get(0,'defaultuicontrolFontSizeMode'));

appdata = [];
appdata.lastValidTag = 'text15';

h29 = uicontrol(...
'Parent',h24,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment','right',...
'String','CV repetition：',...
'Style','text',...
'Position',[0.0224719101123595 0.0576923076923077 0.455056179775281 0.211538461538462],...
'Children',[],...
'Tag','text15',...
'FontSize',8,...
'FontSizeMode',get(0,'defaultuicontrolFontSizeMode'),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'uipanel9';

h30 = uipanel(...
'Parent',h23,...
'FontUnits',get(0,'defaultuipanelFontUnits'),...
'Units',get(0,'defaultuipanelUnits'),...
'Title','Permutation',...
'Tag','uipanel9',...
'Position',[0.556586270871985 0.416666666666667 0.428571428571429 0.508333333333333],...
'Layout',[],...
'FontSize',8,...
'FontSizeMode',get(0,'defaultuipanelFontSizeMode'),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'checkbox1';

h31 = uicontrol(...
'Parent',h30,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','Run Permutation',...
'Style','checkbox',...
'Position',[0.118942731277533 0.1875 0.506607929515419 0.604166666666667],...
'Callback',@(hObject,eventdata)NS_CPM('checkbox1_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'Tag','checkbox1',...
'FontSize',8,...
'FontSizeMode',get(0,'defaultuicontrolFontSizeMode'));

appdata = [];
appdata.lastValidTag = 'In_perm';

h32 = uicontrol(...
'Parent',h30,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','1000',...
'Style','edit',...
'Position',[0.621145374449339 0.270833333333333 0.268722466960352 0.479166666666667],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)NS_CPM('In_perm_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'Enable','off',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)NS_CPM('In_perm_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','In_perm',...
'FontSize',8,...
'FontSizeMode',get(0,'defaultuicontrolFontSizeMode'));

appdata = [];
appdata.lastValidTag = 'checkbox2';

h33 = uicontrol(...
'Parent',h23,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'String','Export consensus features',...
'Style','checkbox',...
'Position',[0.608534322820037 0.166666666666667 0.341372912801484 0.241666666666667],...
'Callback',@(hObject,eventdata)NS_CPM('checkbox2_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','checkbox2',...
'KeyPressFcn',blanks(0),...
'FontSize',8,...
'FontSizeMode',get(0,'defaultuicontrolFontSizeMode'));

appdata = [];
appdata.lastValidTag = 'uipanel7';

h34 = uipanel(...
'Parent',h1,...
'FontUnits',get(0,'defaultuipanelFontUnits'),...
'Units',get(0,'defaultuipanelUnits'),...
'Title','Result reports',...
'ResizeFcn',blanks(0),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','uipanel7',...
'Position',[0.0308747855917667 0.278982200442766 0.93138936535163 0.147909967845659],...
'Layout',[],...
'FontSize',get(0,'defaultuipanelFontSize'));

appdata = [];
appdata.lastValidTag = 'uipanel12';

h35 = uipanel(...
'Parent',h34,...
'FontUnits',get(0,'defaultuipanelFontUnits'),...
'Units',get(0,'defaultuipanelUnits'),...
'Title','Prediction',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'Tag','uipanel12',...
'Position',[0.0206846910555759 0.0577254330807905 0.561958100241195 0.904365118265717],...
'Layout',[]);

appdata = [];
appdata.lastValidTag = 'TextReport1';

h36 = uicontrol(...
'Parent',h35,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment','right',...
'String',blanks(0),...
'Style','text',...
'Position',[0.0186335403726708 0.0394736842105263 0.96583850931677 0.960526315789474],...
'Children',[],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'Tag','TextReport1',...
'FontSize',8,...
'FontSizeMode',get(0,'defaultuicontrolFontSizeMode'));

appdata = [];
appdata.lastValidTag = 'uipanel13';

h37 = uipanel(...
'Parent',h34,...
'FontUnits',get(0,'defaultuipanelFontUnits'),...
'Units',get(0,'defaultuipanelUnits'),...
'Title','Permutation',...
'ResizeFcn',blanks(0),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','uipanel13',...
'Position',[0.577117276389397 0.0577254330807905 0.401958100241195 0.904365118265717],...
'Layout',[]);

appdata = [];
appdata.lastValidTag = 'TextReport2';

h38 = uicontrol(...
'Parent',h37,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment','right',...
'String',blanks(0),...
'Style','text',...
'Position',[0.0570342205323194 0.0428571428571429 0.893536121673004 0.957142857142857],...
'Children',[],...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','TextReport2',...
'FontSize',8,...
'FontSizeMode',get(0,'defaultuicontrolFontSizeMode'));

appdata = [];
appdata.lastValidTag = 'uipanel1';

h39 = uipanel(...
'Parent',h1,...
'FontUnits',get(0,'defaultuipanelFontUnits'),...
'Units',get(0,'defaultuipanelUnits'),...
'ForegroundColor',get(0,'defaultuipanelForegroundColor'),...
'HighlightColor',get(0,'defaultuipanelHighlightColor'),...
'ShadowColor',get(0,'defaultuipanelShadowColor'),...
'BorderType',get(0,'defaultuipanelBorderType'),...
'BorderWidth',get(0,'defaultuipanelBorderWidth'),...
'TitlePosition',get(0,'defaultuipanelTitlePosition'),...
'Title',blanks(0),...
'Visible',get(0,'defaultuipanelVisible'),...
'BackgroundColor',get(0,'defaultuipanelBackgroundColor'),...
'ResizeFcn',blanks(0),...
'HandleVisibility',get(0,'defaultuipanelHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','uipanel1',...
'UserData',[],...
'Position',[0.0307692307692308 0.0873362445414847 0.924786324786325 0.180494905385735],...
'Layout',[],...
'FontSize',8,...
'FontName',get(0,'defaultuipanelFontName'),...
'FontAngle',get(0,'defaultuipanelFontAngle'),...
'FontWeight',get(0,'defaultuipanelFontWeight'));

appdata = [];
appdata.lastValidTag = 'InputText1';

h40 = uicontrol(...
'Parent',h39,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment','right',...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','Data Input：',...
'Style','text',...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[0.0115213720921349 0.821905940594059 0.245062836624776 0.134622524752475],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Callback',blanks(0),...
'Children',[],...
'Tooltip',blanks(0),...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','InputText1',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',get(0,'defaultuicontrolFontSize'),...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'InputText2';

h41 = uicontrol(...
'Parent',h39,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment','right',...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','Scores Input：',...
'Style','text',...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[0.0115213720921349 0.573917079207921 0.245062836624776 0.141707920792079],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Callback',blanks(0),...
'Children',[],...
'Tooltip',blanks(0),...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','InputText2',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',get(0,'defaultuicontrolFontSize'),...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'InputText3';

h42 = uicontrol(...
'Parent',h39,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment','right',...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','Output Directory：',...
'Style','text',...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[0.0115213720921349 0.113366336633663 0.245062836624776 0.148793316831683],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Callback',blanks(0),...
'Children',[],...
'Tooltip',blanks(0),...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','InputText3',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',get(0,'defaultuicontrolFontSize'),...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'In_dat';

h43 = uicontrol(...
'Parent',h39,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment',get(0,'defaultuicontrolHorizontalAlignment'),...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String',blanks(0),...
'Style','edit',...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[0.25 0.792452830188679 0.653984962406015 0.160377358490566],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)NS_CPM('In_dat_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)NS_CPM('In_dat_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','In_dat',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',8,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'In_sco';

h44 = uicontrol(...
'Parent',h39,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment',get(0,'defaultuicontrolHorizontalAlignment'),...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String',blanks(0),...
'Style','edit',...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[0.25 0.566037735849057 0.653984962406015 0.160377358490566],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)NS_CPM('In_sco_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)NS_CPM('In_sco_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','In_sco',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',8,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'In_out';

h45 = uicontrol(...
'Parent',h39,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment',get(0,'defaultuicontrolHorizontalAlignment'),...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String',blanks(0),...
'Style','edit',...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[0.25 0.113207547169811 0.653984962406015 0.160377358490566],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)NS_CPM('In_out_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)NS_CPM('In_out_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','In_out',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',8,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'pushbutton4';

h46 = uicontrol(...
'Parent',h39,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment',get(0,'defaultuicontrolHorizontalAlignment'),...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','...',...
'Style',get(0,'defaultuicontrolStyle'),...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[0.92 0.106298486873463 0.0639097744360904 0.19811320754717],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Callback',@(hObject,eventdata)NS_CPM('pushbutton4_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton4',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',14,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'pushbutton2';

h47 = uicontrol(...
'Parent',h39,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment',get(0,'defaultuicontrolHorizontalAlignment'),...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','...',...
'Style',get(0,'defaultuicontrolStyle'),...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[0.92 0.556691941456533 0.0639097744360902 0.19811320754717],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Callback',@(hObject,eventdata)NS_CPM('pushbutton2_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton2',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',14,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'pushbutton1';

h48 = uicontrol(...
'Parent',h39,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment',get(0,'defaultuicontrolHorizontalAlignment'),...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','...',...
'Style',get(0,'defaultuicontrolStyle'),...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[0.92 0.787843865611213 0.0639097744360904 0.19811320754717],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Callback',@(hObject,eventdata)NS_CPM('pushbutton1_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton1',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',14,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'text11';

h49 = uicontrol(...
'Parent',h39,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment','right',...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','Covariable Input：',...
'Style','text',...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[0.0115213720921349 0.325928217821782 0.245062836624776 0.155878712871287],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Callback',blanks(0),...
'Children',[],...
'Tooltip',blanks(0),...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','text11',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',get(0,'defaultuicontrolFontSize'),...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'pushbutton3';

h50 = uicontrol(...
'Parent',h39,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment',get(0,'defaultuicontrolHorizontalAlignment'),...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String','...',...
'Style',get(0,'defaultuicontrolStyle'),...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[0.92 0.326247937293729 0.0633147113594041 0.2],...
'BackgroundColor',get(0,'defaultuicontrolBackgroundColor'),...
'Callback',@(hObject,eventdata)NS_CPM('pushbutton3_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','pushbutton3',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',14,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));

appdata = [];
appdata.lastValidTag = 'In_cov';

h51 = uicontrol(...
'Parent',h39,...
'Units','normalized',...
'FontUnits',get(0,'defaultuicontrolFontUnits'),...
'HorizontalAlignment',get(0,'defaultuicontrolHorizontalAlignment'),...
'ListboxTop',get(0,'defaultuicontrolListboxTop'),...
'Max',get(0,'defaultuicontrolMax'),...
'Min',get(0,'defaultuicontrolMin'),...
'SliderStep',get(0,'defaultuicontrolSliderStep'),...
'String',blanks(0),...
'Style','edit',...
'Value',get(0,'defaultuicontrolValue'),...
'Position',[0.25 0.336734693877551 0.653620352250489 0.163265306122449],...
'BackgroundColor',[1 1 1],...
'Callback',@(hObject,eventdata)NS_CPM('In_cov_Callback',hObject,eventdata,guidata(hObject)),...
'Children',[],...
'ForegroundColor',get(0,'defaultuicontrolForegroundColor'),...
'Enable',get(0,'defaultuicontrolEnable'),...
'TooltipString',blanks(0),...
'Visible',get(0,'defaultuicontrolVisible'),...
'HandleVisibility',get(0,'defaultuicontrolHandleVisibility'),...
'ButtonDownFcn',blanks(0),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)NS_CPM('In_cov_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'DeleteFcn',blanks(0),...
'Tag','In_cov',...
'UserData',[],...
'KeyPressFcn',blanks(0),...
'KeyReleaseFcn',blanks(0),...
'FontSize',8,...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontAngle',get(0,'defaultuicontrolFontAngle'),...
'FontWeight',get(0,'defaultuicontrolFontWeight'));


hsingleton = h1;


% --- Set application data first then calling the CreateFcn. 
function local_CreateFcn(hObject, eventdata, createfcn, appdata)

if ~isempty(appdata)
   names = fieldnames(appdata);
   for i=1:length(names)
       name = char(names(i));
       setappdata(hObject, name, getfield(appdata,name));
   end
end

if ~isempty(createfcn)
   if isa(createfcn,'function_handle')
       createfcn(hObject, eventdata);
   else
       eval(createfcn);
   end
end


% --- Handles default GUIDE GUI creation and callback dispatch
function varargout = gui_mainfcn(gui_State, varargin)

gui_StateFields =  {'gui_Name'
    'gui_Singleton'
    'gui_OpeningFcn'
    'gui_OutputFcn'
    'gui_LayoutFcn'
    'gui_Callback'};
gui_Mfile = '';
for i=1:length(gui_StateFields)
    if ~isfield(gui_State, gui_StateFields{i})
        error(message('MATLAB:guide:StateFieldNotFound', gui_StateFields{ i }, gui_Mfile));
    elseif isequal(gui_StateFields{i}, 'gui_Name')
        gui_Mfile = [gui_State.(gui_StateFields{i}), '.m'];
    end
end

numargin = length(varargin);

if numargin == 0
    % NS_CPM
    % create the GUI only if we are not in the process of loading it
    % already
    gui_Create = true;
elseif local_isInvokeActiveXCallback(gui_State, varargin{:})
    % NS_CPM(ACTIVEX,...)
    vin{1} = gui_State.gui_Name;
    vin{2} = [get(varargin{1}.Peer, 'Tag'), '_', varargin{end}];
    vin{3} = varargin{1};
    vin{4} = varargin{end-1};
    vin{5} = guidata(varargin{1}.Peer);
    feval(vin{:});
    return;
elseif local_isInvokeHGCallback(gui_State, varargin{:})
    % NS_CPM('CALLBACK',hObject,eventData,handles,...)
    gui_Create = false;
else
    % NS_CPM(...)
    % create the GUI and hand varargin to the openingfcn
    gui_Create = true;
end

if ~gui_Create
    % In design time, we need to mark all components possibly created in
    % the coming callback evaluation as non-serializable. This way, they
    % will not be brought into GUIDE and not be saved in the figure file
    % when running/saving the GUI from GUIDE.
    designEval = false;
    if (numargin>1 && ishghandle(varargin{2}))
        fig = varargin{2};
        while ~isempty(fig) && ~ishghandle(fig,'figure')
            fig = get(fig,'parent');
        end
        
        designEval = isappdata(0,'CreatingGUIDEFigure') || (isscalar(fig)&&isprop(fig,'GUIDEFigure'));
    end
        
    if designEval
        beforeChildren = findall(fig);
    end
    
    % evaluate the callback now
    varargin{1} = gui_State.gui_Callback;
    if nargout
        [varargout{1:nargout}] = feval(varargin{:});
    else       
        feval(varargin{:});
    end
    
    % Set serializable of objects created in the above callback to off in
    % design time. Need to check whether figure handle is still valid in
    % case the figure is deleted during the callback dispatching.
    if designEval && ishghandle(fig)
        set(setdiff(findall(fig),beforeChildren), 'Serializable','off');
    end
else
    if gui_State.gui_Singleton
        gui_SingletonOpt = 'reuse';
    else
        gui_SingletonOpt = 'new';
    end

    % Check user passing 'visible' P/V pair first so that its value can be
    % used by oepnfig to prevent flickering
    gui_Visible = 'auto';
    gui_VisibleInput = '';
    for index=1:2:length(varargin)
        if length(varargin) == index || ~ischar(varargin{index})
            break;
        end

        % Recognize 'visible' P/V pair
        len1 = min(length('visible'),length(varargin{index}));
        len2 = min(length('off'),length(varargin{index+1}));
        if ischar(varargin{index+1}) && strncmpi(varargin{index},'visible',len1) && len2 > 1
            if strncmpi(varargin{index+1},'off',len2)
                gui_Visible = 'invisible';
                gui_VisibleInput = 'off';
            elseif strncmpi(varargin{index+1},'on',len2)
                gui_Visible = 'visible';
                gui_VisibleInput = 'on';
            end
        end
    end
    
    % Open fig file with stored settings.  Note: This executes all component
    % specific CreateFunctions with an empty HANDLES structure.

    
    % Do feval on layout code in m-file if it exists
    gui_Exported = ~isempty(gui_State.gui_LayoutFcn);
    % this application data is used to indicate the running mode of a GUIDE
    % GUI to distinguish it from the design mode of the GUI in GUIDE. it is
    % only used by actxproxy at this time.   
    setappdata(0,genvarname(['OpenGuiWhenRunning_', gui_State.gui_Name]),1);
    if gui_Exported
        gui_hFigure = feval(gui_State.gui_LayoutFcn, gui_SingletonOpt);

        % make figure invisible here so that the visibility of figure is
        % consistent in OpeningFcn in the exported GUI case
        if isempty(gui_VisibleInput)
            gui_VisibleInput = get(gui_hFigure,'Visible');
        end
        set(gui_hFigure,'Visible','off')

        % openfig (called by local_openfig below) does this for guis without
        % the LayoutFcn. Be sure to do it here so guis show up on screen.
        movegui(gui_hFigure,'onscreen');
    else
        gui_hFigure = local_openfig(gui_State.gui_Name, gui_SingletonOpt, gui_Visible);
        % If the figure has InGUIInitialization it was not completely created
        % on the last pass.  Delete this handle and try again.
        if isappdata(gui_hFigure, 'InGUIInitialization')
            delete(gui_hFigure);
            gui_hFigure = local_openfig(gui_State.gui_Name, gui_SingletonOpt, gui_Visible);
        end
    end
    if isappdata(0, genvarname(['OpenGuiWhenRunning_', gui_State.gui_Name]))
        rmappdata(0,genvarname(['OpenGuiWhenRunning_', gui_State.gui_Name]));
    end

    % Set flag to indicate starting GUI initialization
    setappdata(gui_hFigure,'InGUIInitialization',1);

    % Fetch GUIDE Application options
    gui_Options = getappdata(gui_hFigure,'GUIDEOptions');
    % Singleton setting in the GUI MATLAB code file takes priority if different
    gui_Options.singleton = gui_State.gui_Singleton;

    if ~isappdata(gui_hFigure,'GUIOnScreen')
        % Adjust background color
        if gui_Options.syscolorfig
            set(gui_hFigure,'Color', get(0,'DefaultUicontrolBackgroundColor'));
        end

        % Generate HANDLES structure and store with GUIDATA. If there is
        % user set GUI data already, keep that also.
        data = guidata(gui_hFigure);
        handles = guihandles(gui_hFigure);
        if ~isempty(handles)
            if isempty(data)
                data = handles;
            else
                names = fieldnames(handles);
                for k=1:length(names)
                    data.(char(names(k)))=handles.(char(names(k)));
                end
            end
        end
        guidata(gui_hFigure, data);
    end

    % Apply input P/V pairs other than 'visible'
    for index=1:2:length(varargin)
        if length(varargin) == index || ~ischar(varargin{index})
            break;
        end

        len1 = min(length('visible'),length(varargin{index}));
        if ~strncmpi(varargin{index},'visible',len1)
            try set(gui_hFigure, varargin{index}, varargin{index+1}), catch break, end
        end
    end

    % If handle visibility is set to 'callback', turn it on until finished
    % with OpeningFcn
    gui_HandleVisibility = get(gui_hFigure,'HandleVisibility');
    if strcmp(gui_HandleVisibility, 'callback')
        set(gui_hFigure,'HandleVisibility', 'on');
    end

    feval(gui_State.gui_OpeningFcn, gui_hFigure, [], guidata(gui_hFigure), varargin{:});

    if isscalar(gui_hFigure) && ishghandle(gui_hFigure)
        % Handle the default callbacks of predefined toolbar tools in this
        % GUI, if any
        guidemfile('restoreToolbarToolPredefinedCallback',gui_hFigure); 
        
        % Update handle visibility
        set(gui_hFigure,'HandleVisibility', gui_HandleVisibility);

        % Call openfig again to pick up the saved visibility or apply the
        % one passed in from the P/V pairs
        if ~gui_Exported
            gui_hFigure = local_openfig(gui_State.gui_Name, 'reuse',gui_Visible);
        elseif ~isempty(gui_VisibleInput)
            set(gui_hFigure,'Visible',gui_VisibleInput);
        end
        if strcmpi(get(gui_hFigure, 'Visible'), 'on')
            figure(gui_hFigure);
            
            if gui_Options.singleton
                setappdata(gui_hFigure,'GUIOnScreen', 1);
            end
        end

        % Done with GUI initialization
        if isappdata(gui_hFigure,'InGUIInitialization')
            rmappdata(gui_hFigure,'InGUIInitialization');
        end

        % If handle visibility is set to 'callback', turn it on until
        % finished with OutputFcn
        gui_HandleVisibility = get(gui_hFigure,'HandleVisibility');
        if strcmp(gui_HandleVisibility, 'callback')
            set(gui_hFigure,'HandleVisibility', 'on');
        end
        gui_Handles = guidata(gui_hFigure);
    else
        gui_Handles = [];
    end

    if nargout
        [varargout{1:nargout}] = feval(gui_State.gui_OutputFcn, gui_hFigure, [], gui_Handles);
    else
        feval(gui_State.gui_OutputFcn, gui_hFigure, [], gui_Handles);
    end

    if isscalar(gui_hFigure) && ishghandle(gui_hFigure)
        set(gui_hFigure,'HandleVisibility', gui_HandleVisibility);
    end
end

function gui_hFigure = local_openfig(name, singleton, visible)

% openfig with three arguments was new from R13. Try to call that first, if
% failed, try the old openfig.
if nargin('openfig') == 2
    % OPENFIG did not accept 3rd input argument until R13,
    % toggle default figure visible to prevent the figure
    % from showing up too soon.
    gui_OldDefaultVisible = get(0,'defaultFigureVisible');
    set(0,'defaultFigureVisible','off');
    gui_hFigure = matlab.hg.internal.openfigLegacy(name, singleton);
    set(0,'defaultFigureVisible',gui_OldDefaultVisible);
else
    % Call version of openfig that accepts 'auto' option"
    gui_hFigure = matlab.hg.internal.openfigLegacy(name, singleton, visible);  
%     %workaround for CreateFcn not called to create ActiveX
%         peers=findobj(findall(allchild(gui_hFigure)),'type','uicontrol','style','text');    
%         for i=1:length(peers)
%             if isappdata(peers(i),'Control')
%                 actxproxy(peers(i));
%             end            
%         end
end

function result = local_isInvokeActiveXCallback(gui_State, varargin)

try
    result = ispc && iscom(varargin{1}) ...
             && isequal(varargin{1},gcbo);
catch
    result = false;
end

function result = local_isInvokeHGCallback(gui_State, varargin)

try
    fhandle = functions(gui_State.gui_Callback);
    result = ~isempty(findstr(gui_State.gui_Name,fhandle.file)) || ...
             (ischar(varargin{1}) ...
             && isequal(ishghandle(varargin{2}), 1) ...
             && (~isempty(strfind(varargin{1},[get(varargin{2}, 'Tag'), '_'])) || ...
                ~isempty(strfind(varargin{1}, '_CreateFcn'))) );
catch
    result = false;
end
